permalink: pretty
markdown: kramdown
theme: null

title: The Bitcoin Cash 0.1 Specification
author: n9jd34x04l151ho4 + topolino + kenman345
description:
    A vocabulary and associated APIs for Bitcoin Cash
url: https://spec.consortium.cash
repo: https://github.com/bigearth/spec.bitbox.earth
img: img/logo.png
lang: en-US
sass:
    sass_dir: _includes/_sass
    style: compressed
plugins:
  - jekyll-minifier
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      # Page Variables
      image: img/logo.png
      link_tweet: "Tweet to @TWITTERHANDLE"
      link_facebook: "Write on @FACEBOOKHANDLE's wall"
      email_subject: "Please%20consider%20accepting%20Bitcoin%20Cash%20payments"
      rtfm: "Read support docs from"
      link_mobile: "TWEET THEM"
      workonit_tweet: "Please consider accepting #BitcoinCash for payments @TWITTERHANDLE - itâ€™s \"Peer-to-Peer Electronic Cash\" that is fast, reliable, and secure, with low fees. More @"
      link_progress: "Thank them for accepting Bitcoin Cash"
      link_progress_mobile: "THANK THEM"
      progress_tweet: "Thanks for accepting Bitcoin Cash, @TWITTERHANDLE!"
      hash: "acceptBitcoinCash, BCHforEveryone"
      has_search: yes
      list_of: "method"
      encoded_img_placeholder: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="
      img_placeholder: "/img/placeholder.png"

exclude:
    - CNAME
    - CONTRIBUTING.md
    - EXCLUSION.md
    - Gemfile
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
    - vendor
    - kube
    - nginx.conf
    - scripts
    - Dockerfile
    - static.json
    - sections_schema.yml
    - websites_schema.yml

jekyll-minifier:
  compress_javascript: true         # Default: true
  exclude: ['data.json', 'stats.json', 'robots.txt'] # Keeping these files sexy guys
